select * from cisadm.ci_cust_cl;

select * from cisadm.ci_prem;

select * from cisadm.ci_prem_type
where prem_type_cd = 'COM-S';

SELECT * FROM CISADM.CI_TREND_AREA;

SELECT * FROM CISADM.CI_PREM A
WHERE NOT EXISTS (SELECT * FROM CISADM.CI_PREM_TYPE WHERE TRIM(PREM_TYPE_CD) = TRIM(A.PREM_TYPE_CD));
---------------------------------------------------------------------------------------------------------------------------------------------
--VALIDATION FOR CI_PER TABLE CDS

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_PER' AND 
COLUMN_NAME LIKE '%CD';

--LANGUAGE_CD
SELECT * FROM CISADM.CI_LANGUAGE;
SELECT * FROM 
CISADM.CI_PER PER
WHERE NOT EXISTS( SELECT * FROM CISADM.CI_LANGUAGE WHERE TRIM(LANGUAGE_CD)= TRIM(PER.LANGUAGE_CD)); 

--TIME_ZONE_CD
SELECT * FROM 
CISADM.CI_PER PER
WHERE NOT EXISTS( SELECT * FROM CISADM.CI_TIME_ZONE WHERE TRIM(TIME_ZONE_CD)= TRIM(PER.TIME_ZONE_CD));

---------------------------------------------------------------------------------------------------------------------

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_PER_NAME'
AND 
COLUMN_NAME LIKE '%CD';

SELECT * FROM CI_PER_NAME;

SELECT * FROM CISADM.CI_NAME_TYPE;
----------------------------------------------------------------------------------------------------------------------------------
-- THERE IS NO CD IN PER_NAME
SELECT * FROM CISADM.CI_PER_NAME PN
WHERE NOT EXISTS( SELECT * FROM CISADM.CI_NAME_TYPE WHERE TRIM(NAME_TYPE_FLG) = TRIM(PN.NAME_TYPE_FLG));
--------------------------------------------------------------------------------------------------------------------
-- VALIDATION FOR CI_ACCT

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_ACCT'
AND COLUMN_NAME LIKE '%CD';

-- VALIDATION FOR BILL_CYC_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_BILL_CYC WHERE TRIM(BILL_CYC_CD) = TRIM(ACCT.BILL_CYC_CD));

--VALIDATION FOR CURRENCY_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CISADM.CI_CURRENCY_CD WHERE TRIM(CURRENCY_CD) = TRIM(ACCT.CURRENCY_CD));

--VALIDATION FOR ACCT_MGMT_GRP_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_ACCT_MGMT_GR WHERE TRIM(ACCT_MGMT_GRP_CD) = TRIM(ACCT.ACCT_MGMT_GRP_CD));

--VALIDATION FOR COLL_CL_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_COLL_CL WHERE TRIM(COLL_CL_CD) = TRIM(ACCT.COLL_CL_CD));

--VALIDATION FOR CUST_CL_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_CUST_CL WHERE TRIM(CUST_CL_CD) = TRIM(ACCT.CUST_CL_CD));

--VALIDATION FOR BUD_PLAN_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_BUD_PLAN WHERE TRIM(BUD_PLAN_CD) = TRIM(ACCT.BUD_PLAN_CD));

--VALIDATION FOR ACCESS_GRP_CD
SELECT * FROM CI_ACCT ACCT
WHERE NOT EXISTS(SELECT * FROM CI_ACC_GRP WHERE TRIM(ACCESS_GRP_CD) = TRIM(ACCT.ACCESS_GRP_CD));

--------------------------------------------------------------------------------------------------------------------
-- VALIDATION FOR CI_ACCT_PER

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_ACCT_PER'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR ACCT_REL_TYPE_CD
SELECT * FROM CI_ACCT_PER ACCTP
WHERE NOT EXISTS(SELECT * FROM CI_ACCT_REL_TYP WHERE TRIM(ACCT_REL_TYPE_CD) = TRIM(ACCTP.ACCT_REL_TYPE_CD));

--VALIDATION FOR BILL_RTE_TYPE_CD
SELECT * FROM CI_ACCT_PER ACCTP
WHERE NOT EXISTS(SELECT * FROM CI_BILL_RT_TYPE WHERE TRIM(BILL_RTE_TYPE_CD) = TRIM(ACCTP.BILL_RTE_TYPE_CD));

--VALIDATION FOR QTE_RTE_TYPE_CD
SELECT * FROM CI_ACCT_PER ACCTP
WHERE NOT EXISTS(SELECT * FROM CI_QTE_RTE_TYPE WHERE TRIM(QTE_RTE_TYPE_CD) = TRIM(ACCTP.QTE_RTE_TYPE_CD));
--------------------------------------------------------------------------------------------------------------------
-- VALIDATION FOR CI_PREM

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_PREM'
AND COLUMN_NAME LIKE '%CD';

-- VALIDATION FOR TIME_ZONE_CD
SELECT * FROM CI_PREM PREM
WHERE NOT EXISTS(SELECT * FROM CI_TIME_ZONE WHERE TRIM(TIME_ZONE_CD) = TRIM(PREM.TIME_ZONE_CD));

-- VALIDATION FOR PREM_TYPE_CD
SELECT * FROM CI_PREM PREM
WHERE NOT EXISTS(SELECT * FROM CI_PREM_TYPE WHERE TRIM(PREM_TYPE_CD) = TRIM(PREM.PREM_TYPE_CD));

--VALIDATION FOR MR_INSTR_CD
SELECT * FROM CI_PREM PREM
WHERE NOT EXISTS(SELECT * FROM CI_MR_INSTR WHERE TRIM(MR_INSTR_CD) = TRIM(PREM.MR_INSTR_CD));

--VALIDATION FOR MR_WARN_CD
SELECT * FROM CI_PREM PREM
WHERE NOT EXISTS(SELECT * FROM CI_MR_WARN WHERE TRIM(MR_WARN_CD) = TRIM(PREM.MR_WARN_CD));

--VALIDATION FOR TREND_AREA_CD
SELECT * FROM CI_PREM PREM
WHERE NOT EXISTS(SELECT * FROM CI_TREND_AREA WHERE TRIM(TREND_AREA_CD) = TRIM(PREM.TREND_AREA_CD));
--------------------------------------------------------------------------------------------------------------------
-- VALIDATION FOR CI_SA

SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_SA'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR NB_RULE_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_NB_RULE WHERE TRIM(NB_RULE_CD) = TRIM(SA.NB_RULE_CD));

--VALIDATION FOR PROP_DCL_RSN_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_PROP_DCL_RSN WHERE TRIM(PROP_DCL_RSN_CD) = TRIM(SA.PROP_DCL_RSN_CD));

--VALIDATION FOR SA_TYPE_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_SA_TYPE WHERE TRIM(SA_TYPE_CD) = TRIM(SA.SA_TYPE_CD));

--VALIDATION FOR START_OPT_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_START_OPT WHERE TRIM(START_OPT_CD) = TRIM(SA.START_OPT_CD));

-- VALIDATION FOR SIC_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_SIC WHERE TRIM(SIC_CD) = TRIM(SA.SIC_CD));

--VALIDATION FOR CURRENCY_CD
SELECT * FROM CI_SA SA
WHERE NOT EXISTS(SELECT * FROM CI_CURRENCY_CD WHERE TRIM(CURRENCY_CD) = TRIM(SA.CURRENCY_CD));
--------------------------------------------------------------------------------------------------------------------
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_SA_SP'
AND COLUMN_NAME LIKE '%CD';

SELECT * FROM CI_SA_SP;
-- NO CD AVAILABLE HERE 
---------------------------------------------------------------------------------------------------------------------
--VALIDATION FOR TABLE SP
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_SP'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR DISCON_LOC_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_DISCON_LOC WHERE TRIM(DISCON_LOC_CD) = TRIM(SP.DISCON_LOC_CD));

--VALIDATION FOR SP_TYPE_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_SP_TYPE WHERE TRIM(SP_TYPE_CD) = TRIM(SP.SP_TYPE_CD));

--VALIDATION FOR MR_CYC_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_MR_CYC WHERE TRIM(MR_CYC_CD) = TRIM(SP.MR_CYC_CD));

--VALIDATION FOR MR_RTE_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_MR_RTE WHERE TRIM(MR_RTE_CD) = TRIM(SP.MR_RTE_CD));

--VALIDATION FOR MTR_LOC_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_MTR_LOC WHERE TRIM(MTR_LOC_CD) = TRIM(SP.MTR_LOC_CD));

--VALIDATION FOR FAC_LVL_1_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_FAC_LVL_1 WHERE TRIM(FAC_LVL_1_CD) = TRIM(SP.FAC_LVL_1_CD));

--VALIDATION FOR FAC_LVL_2_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_FAC_LVL_2 WHERE TRIM(FAC_LVL_2_CD) = TRIM(SP.FAC_LVL_2_CD));

--VALIDATION FOR FAC_LVL_3_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_FAC_LVL_3 WHERE TRIM(FAC_LVL_3_CD) = TRIM(SP.FAC_LVL_3_CD));

--VALIDATION FOR MR_INSTR_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_MR_INSTR WHERE TRIM(MR_INSTR_CD) = TRIM(SP.MR_INSTR_CD));

--VALIDATION FOR MR_WARN_CD
SELECT * FROM CI_SP SP
WHERE NOT EXISTS(SELECT * FROM CI_MR_WARN WHERE TRIM(MR_WARN_CD) = TRIM(SP.MR_WARN_CD));
-------------------------------------------------------------------------------------------------------------------

--VALIDATION FOR TABLE SP_MTR_HIST
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_SP_MTR_HIST'
AND COLUMN_NAME LIKE '%CD';

SELECT * FROM CI_SP_MTR_HIST;

-- THERE IS NO CD AVAILABLE 
--------------------------------------------------------------------------------------------------------------------

--VALIDATION FOR TABLE MTR_CONFIG
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_MTR_CONFIG'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR MTR_CONFIG_TY_CD

SELECT * FROM CI_MTR_CONFIG MC
WHERE NOT EXISTS( SELECT * FROM CI_MTR_CONFIG_TY WHERE TRIM(MTR_CONFIG_TY_CD) = TRIM(MC.MTR_CONFIG_TY_CD));

---------------------------------------------------------------------------------------------------------------------

-- VALIDATION FOR TABLE MTR
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_MTR'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR MTR_TYPE_CD
SELECT * FROM CI_MTR MTR
WHERE NOT EXISTS( SELECT * FROM CI_MTR_TYPE WHERE TRIM(MTR_TYPE_CD) = TRIM(MTR.MTR_TYPE_CD));

--VALIDATION FOR MFG_CD
SELECT * FROM CI_MTR MTR
WHERE NOT EXISTS( SELECT * FROM CI_MFG WHERE TRIM(MFG_CD) = TRIM(MTR.MFG_CD));

--VALIDATION FOR MODEL_CD
SELECT * FROM CI_MTR MTR
WHERE NOT EXISTS( SELECT * FROM CI_MODEL WHERE TRIM(MODEL_CD) = TRIM(MTR.MODEL_CD));

--VALIDATION FOR RETIRE_RSN_CD
SELECT * FROM CI_MTR MTR
WHERE NOT EXISTS( SELECT * FROM CI_RETIRE_RSN WHERE TRIM(RETIRE_RSN_CD) = TRIM(MTR.RETIRE_RSN_CD));
------------------------------------------------------------------------------------------------------------------------
-- VALIDATION FOR TABLE MR
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_MR'
AND COLUMN_NAME LIKE '%CD';

--VALIDATION FOR MR_SOURCE_CD
SELECT COUNT(MR_SOURCE_CD) FROM CI_MR MR
WHERE NOT EXISTS( SELECT * FROM CI_MR_SOURCE WHERE TRIM(MR_SOURCE_CD) = TRIM(MR.MR_SOURCE_CD));

--ERROR FIXING
UPDATE CI_MR
SET MR_SOURCE_CD = 'IVR'
WHERE MR_SOURCE_CD = ' ';
-------------------------------------------------------------------------------------------------------------------------
SELECT * FROM CI_REG;
-- VALIDATION FOR TABLE REG
SELECT * FROM ALL_TAB_COLUMNS
WHERE TABLE_NAME = 'CI_REG'
AND COLUMN_NAME LIKE '%CD';

